name: Run Integration Test
on:
  workflow_dispatch:
    inputs:
      connector:
        description: "Airbyte Connector"
        required: true
      repo:
        description: "Repo to check out code from. Defaults to the main airbyte repo. Set this when building connectors from forked repos."
        required: false
        default: "airbytehq/airbyte"
      gitref:
        description: "The git ref to check out from the specified repository."
        required: false
        default: master
      comment-id:
        description: "The comment-id of the slash command. Used to update the comment with the status."
        required: false
      uuid:
        description: "Custom UUID of workflow run. Used because GitHub dispatches endpoint does not return workflow run id."
        required: false
      connector-acceptance-test-version:
        description: "Set a specific connector acceptance test version to use. Enter 'dev' to test, build and use a local version of Connector Acceptance Test."
        required: false
        default: "latest"
      local_cdk:
        description: "Run Connector Acceptance Tests against the CDK version on the current branch."
        required: false

jobs:
  uuid:
    name: "Custom UUID of workflow run"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: UUID ${{ github.event.inputs.uuid }}
        run: true
  integration-test:
    timeout-minutes: 240
    runs-on: ubuntu-latest
    steps:
      - name: Test ${{ github.event.inputs.connector }}
        id: test
        env:
          ACTION_RUN_ID: ${{github.run_id}}
          # Oracle expects this variable to be set. Although usually present, this is not set by default on Github virtual runners.
          TZ: UTC
          ORG_GRADLE_PROJECT_connectorAcceptanceTestVersion: ${{github.event.inputs.connector-acceptance-test-version}}
        uses: Wandalen/wretry.action@master
        with:
          command: echo "inputs.connector=${{ github.event.inputs.connector }} inputs.local_cdk=${{ github.event.inputs.local_cdk }}"
          attempt_limit: 3
          attempt_delay: 10000 # in ms
